apt update
apt install sudo -y
apt install qemu-kvm -y
apt install ssh -y
apt install wget -y
apt install curl -y
wget -O win.iso https://dl.bobpony.com/windows/server/2016/en_windows_server_2016_updated_feb_2018_x64_dvd_11636692.iso
wget -O virtio.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.271-1/virtio-win-0.1.271.iso
qemu-img create -f qcow2 disk.qcow2 30G
sudo qemu-system-x86_64 \
-M q35,nvdimm=on,hmat=on \
-usb -device usb-tablet -device usb-kbd \
-cpu qemu64,+ssse3,+sse4.1,+sse4.2,+aes,+xsave,+xsaveopt,+xsavec,+xgetbv1,+avx,+avx2,+fma,+fma4,+popcnt,+cx16,+mmx,+sse,+sse2,+x2apic,+lahf_lm,+rdrand \
-smp sockets=1,cores=8,threads=1 \
-object memory-backend-memfd,id=mem,size=8192M,share=on,prealloc=on \
-m 8192 -mem-prealloc -machine memory-backend=mem \
-drive file=disk.qcow2,if=none,format=qcow2,cache=unsafe,aio=threads,discard=on,id=hd0 \
-device virtio-blk-pci,drive=hd0 \
-drive file=win.iso,media=cdrom,if=none,id=cdrom0 \
-device ahci,id=ahci0 \
-device ide-cd,drive=cdrom0,bus=ahci0.0 \
-drive file=virtio.iso,media=cdrom,if=none,id=cdrom1 \
-device ide-cd,drive=cdrom1,bus=ahci0.1 \
-device qxl-vga,vgamem_mb=2048,ram_size=268435456,vram_size=268435456 \
-device virtio-balloon,id=balloon0 \
-display vnc=:0 \
-netdev user,id=n0,hostfwd=tcp::3389-:3389,restrict=off -device virtio-net-pci,netdev=n0 \
-accel tcg,thread=multi,tb-size=34388608,split-wx=on \
-no-hpet \
-rtc clock=host,base=utc \
-boot order=d,menu=on \
-daemonize
ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:localhost:5900 tcp@a.pinggy.io
